### ISSUE TITLE
UML frame appears broken in export

### ISSUE THREAD

**Issue by F30** [rlespinasse/docker-drawio-desktop-headless#20]
Please consider the attached Draw.io diagram. It contains two UML *frames*. While the left one always renders fine, the right one appears as a black box when exported using the Draw.io Desktop Headless Docker image:

![frame-bug-bad](https://user-images.githubusercontent.com/2017238/136027111-aa0e3fab-e473-46be-9162-4afd449bcc9f.png)

It should look like this:

![frame-bug-good](https://user-images.githubusercontent.com/2017238/136027205-97cdde2c-8ffb-4236-a00b-85b46c165542.png)

This happens both when exporting to SVG and PNG. The command I used is a plain `-x -f svg frame-bug.drawio`.

The export works fine using the `draw.io` CLI on macOS. I unfortunately don't have a Linux desktop machine at hand to test it there.

**Attachement:**
[Diagram source file and SVG exports](https://github.com/rlespinasse/docker-drawio-desktop-headless/files/7285996/frame-bug.zip)

**Comment by rlespinasse** [comment]
@F30 Can you tell me the drawio desktop version you used to generate the `good` export?
