### ISSUE TITLE
Add fonts-liberation dependency

### ISSUE THREAD

**Issue by juananpe** [rlespinasse/docker-drawio-desktop-headless#35]
I tried the docker-drawio-desktop-headless as a GitHub action (using https://github.com/rlespinasse/drawio-export-action) and it worked like a charm. However, the current docker-drawio-desktop-headless uses system fonts and these fonts are very limited in docker instances. I understand why this is the case - limiting storage usage - but could you please add the fonts-liberation package here https://github.com/rlespinasse/docker-drawio-desktop-headless/blob/v1.x/Dockerfile#L7?  

The problem is that the default font (Helvetica-12pt) in drawio is not available by default in the docker image, and thus, the resulting PNG images look ugly (with some strings drawn out of the boxes)

Example:

This is what I get after running drawio-export-action: (look at the "Berkeley" node on the right side of the picture)![image](https://user-images.githubusercontent.com/1078305/232245290-7c40310c-54e3-47ce-ad36-907b382783a8.png)

This is what I would expect:
![image](https://user-images.githubusercontent.com/1078305/232245302-79a021fa-fb57-4b1e-8eda-603ac8263c81.png)

Thanks for your work and help

**Comment by rlespinasse** [comment]
The additional fonts are available on

- https://github.com/rlespinasse/drawio-export/releases/tag/v4.8.0
- https://github.com/rlespinasse/drawio-export-action/releases/tag/v2.6.0
