### ISSUE TITLE
Export with user permissions fails

### ISSUE THREAD

**Issue by fragmuffin** [rlespinasse/docker-drawio-desktop-headless#69]
# Problem Description

Exports create files owned by `root`.

Attempting to run with user permissions fails with:

```
touch: cannot touch '/opt/drawio-desktop/unwanted-lines.txt': Permission denied
```

## Replicate issue

Create any diagram called `diagram.drawio`, then attempt an export with user-permissions:

```bash
$ docker run --rm -it -w /data -v $(pwd):/data \
    -u $(id -u):$(id -g) \
    rlespinasse/drawio-desktop-headless:v1.24.0 \
    -x -o diagram.drawio.png diagram.drawio
touch: cannot touch '/opt/drawio-desktop/unwanted-lines.txt': Permission denied
```

## Why is this a problem?

personally:\
Automating image exports on a CI server (Jenkins), files owned by `root` cause future attempts to clean a build fail, causing future CI tasks on that branch to fail.

**Comment by rlespinasse** [comment]
With #71, you will be able to run as non-root
```
docker run -it -u $(id -u):$(id -g) -e HOME=/data/home -w /data -v $(pwd):/data rlespinasse/drawio-desktop-headless
```

> [!CAUTION]
> You will need `-e HOME=/data/<whatever>`
